### ISSUE TITLE
Friendly config

### ISSUE THREAD

**Issue by miholeus** [rocketeers/rocketeer#703]
I've worked with rocketeer for 2 months and got a lot of problems with its configuration.
It's not easy to set specific settings for each environment separately.
The only way to do so is to use config.php and set `connections` and `on` settings or to set settings in **connections** folder.

The first problem I've encountered was the difficulty while using specific settings. I decided to write my own notification system plugin using telegram. 

Documentation (http://rocketeer.autopergamene.eu/II-Concepts/Plugins.html) shows us to use separate folder with plugin sources. I think it's not a good idea, I do not want to have my config separated by dozens of files in different places. So I decided to create my own file, and I could not find the way to include it in the main config. The only solution I found was to create my own bootstrap file and include it with require_once in config.php.

The other problem was the impossibility to hide secret data.
I've used my private key, pass for connecting to server, and also secret keys for notification system plugin.

I decided to share the project with my colleagues, but I didn't want to show them my data.
So we have n people, each with its own settings.
It's impossible now to use such configuration with ease. Why not to use Symfony way where you have parameters.yml (private file) and config.yml (public file)? And these two files are merged by application itself.

So I created 2 files - config.yml and parameters.yml. They look this way:

```
base:
    config:
        host: ''
        username: test
        password: test
        key: ''
        keyphrase: ''
        agent: ''
        db_role: true
    scm:
        username: ~
        password: ~
    strategies: ~
    remote:
        db:
            host: 127.0.0.1
            user: ~
            password: ~
            database: ~

staging:
    config:
        host: host.local
    _extends: base

production:
    config:
        host: some-host.local
    _extends: base

```

Here we have main settings under `base` and each server settings. 
I've extended Symfony Yaml component and included _extends option. So you can merge different sections with ease.
My private data now is located in **parameters.yml**, my colleagues do the same. It's all good now.
I think this format (yml) is more suitable for rocketeer.

Would you you not mind if I redesigned the configuration system and sent you PR?
I think it will be more friendly for everyone to use such configs.
