### ISSUE TITLE
Decouple from Laravel

### ISSUE THREAD

**Issue by henrikbjorn** [rocketeers/rocketeer#8]
Because the project is heavy coupled with Laravel it is not easily used outside of that Context. This could be fixed by using a configuration file like `rocketeer.yml` and replace the list of tasks and closures with an extension interface as the one found in PhpSpec2 https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/Console/Application.php#L336 and https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/Extension/ExtensionInterface.php which can be used like descriped here https://github.com/henrikbjorn/PhpSpecCodeCoverageExtension. Last instead of having it tie commands to artisan, it should ship with its own bin file proberly called `rocketeer`.

It sound like a lot of work, but would make adopting it much easier and more attraktive.

``` yaml
# This is an example file for Rocketeer Issue #8 on Github.
# Advantages for yaml, is the consise syntax also it still
# supports comments and its increased readability
connections: ['production']

git:
    repository: https://github.com/vendor/website.git
    username: foo
    password: bar
    branch: master

remote:
    root_directory: /home/www
    application_name: vendor-website
    keep_released: 4
    shared: []

# The composer extension could be in rocketeer and also
# a couple of framework specifics, which should be explicitly
# added here on a per project basis.
extensions:
    - Rocketeer\Extension\ComposerExtension
    - Rocketeer\Extension\LaravelExtension
    - Rocketeer\Extension\SymfonyExtension
```
